replicaCount: 1

global: 
  leaderElection:
    namespace: cert-manager


installCRDs: true

prometheus:
  enabled: true 

extraArgs:
  - --issuer-ambient-credentials=true
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53