apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - chart: cert-manager
        namespace: cert-manager
        repoURL: https://charts.jetstack.io
        version: v1.12.3
      - chart: crossplane
        namespace: crossplane
        repoURL: https://charts.crossplane.io/stable
        version: 1.13.2
      - chart: external-secrets
        namespace: external-secrets
        repoURL: https://charts.external-secrets.io
        version: 0.9.4
  template:
    metadata:
      name: "{{ chart }}"
    spec:
      project: default
      sources:
        - chart: "{{ chart }}"
          repoURL: "{{ repoURL }}"
          targetRevision: "{{ version }}"
          helm:
            releaseName: "{{ chart }}"
            valueFiles:
              - $values/argocd/dev/values/{{ chart }}.yaml
        - repoURL: https://github.com/mo-abdallaa/argo-c.git
          targetRevision: HEAD
          ref: values
      destination:
        name: in-cluster
        namespace: "{{ namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - createNamespace=true
