apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/mo-abdallaa/argo-c.git
          revision: main
          directories:
          - path: argocd/dev/services/*
          #pathParamPrefix: services
      # - git:
      #     repoURL: https://github.com/mo-abdallaa/argo-c.git
      #     revision: main
      #     files:
      #     - path: values/argocd/values/dev/{{ services.path.basename }}.yaml"
      #     pathParamPrefix: values
  template:
    metadata:
      name: '{{ services.path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mo-abdallaa/argo-c.git
        targetRevision: HEAD
        path: '{{ path }}'
        helm:
          releaseName: '{{ path.basename }}'
      destination:
        name: in-cluster
        namespace: 'tools-{{ path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true