apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/mo-abdallaa/argo-c.git
      revision: main
      directories:
      - path: argocd/dev/services/*
  # - matrix:
  #     generators:
  #     - git:
  #         repoURL: https://github.com/mo-abdallaa/argo-c.git
  #         revision: main
  #         directories:
  #         - path: argocd/dev/services/*
  #         #pathParamPrefix: services
  #     - git:
  #         repoURL: https://github.com/mo-abdallaa/argo-c.git
  #         revision: main
  #         files:
  #         - path: values/argocd/values/*/*.yaml"
  #         pathParamPrefix: values
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mo-abdallaa/argo-c.git
        targetRevision: main
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: 'tools-{{ path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
